sudo: false
language: ruby

rvm:
- ruby-head
- 2.4.1
- 2.3.3
- 2.2
- 2.1
- 2.0
- jruby-head
- jruby-9.1.8.0

cache:
- bundler

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: 2.0
#   fast_finish: true
